#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$HOME/bacillus_amr"
ACCESSIONS="${PROJECT_DIR}/01_genomes/selected_accessions.txt"

DEHYDRATED_ZIP="${PROJECT_DIR}/01_genomes/selected_genomes_dehydrated.zip"
DOWNLOAD_DIR="${PROJECT_DIR}/01_genomes/ncbi_dataset"

LOG="${PROJECT_DIR}/logs/06_download_selected_genomes.log"

cd "$PROJECT_DIR"

{
    echo "BACILLUS AMR PROJECT"
    echo "STEP 06 - DOWNLOAD SELECTED GENOMES"
    echo "Method: NCBI Datasets dehydrated package + rehydrate"
    echo "Started: $(date --iso-8601=seconds)"
    echo

    echo "Accession file: ${ACCESSIONS}"
    echo "Number of accessions: $(wc -l < "${ACCESSIONS}")"
    echo "Accession SHA256:"
    sha256sum "${ACCESSIONS}"
    echo

    # Remove only products generated by THIS workflow.
    # The previous interrupted selected_genomes.zip is deliberately untouched.
    rm -f "${DEHYDRATED_ZIP}"
    rm -rf "${DOWNLOAD_DIR}"

    echo "Creating dehydrated NCBI package..."

    datasets download genome accession \
        --inputfile "${ACCESSIONS}" \
        --include genome \
        --dehydrated \
        --filename "${DEHYDRATED_ZIP}"

    echo
    echo "Extracting dehydrated package..."

    mkdir -p "${DOWNLOAD_DIR}"

    unzip -q "${DEHYDRATED_ZIP}" \
        -d "${DOWNLOAD_DIR}"

    echo
    echo "Files scheduled for rehydration:"

    datasets rehydrate \
        --directory "${DOWNLOAD_DIR}" \
        --list | wc -l

    echo
    echo "Rehydrating genomic FASTA files..."

    datasets rehydrate \
        --directory "${DOWNLOAD_DIR}" \
        --max-workers 5

    echo
    echo "Counting downloaded genomic FASTA files..."

    GENOME_COUNT=$(
        find "${DOWNLOAD_DIR}/ncbi_dataset/data" \
            -type f \
            -name "*_genomic.fna" | wc -l
    )

    echo "Downloaded genomic FASTA files: ${GENOME_COUNT}"

    echo
    echo "Dehydrated archive SHA256:"
    sha256sum "${DEHYDRATED_ZIP}"

    echo
    echo "Finished: $(date --iso-8601=seconds)"

} 2>&1 | tee "${LOG}"
